### ISSUE TITLE
Storm or storms?

### ISSUE THREAD

**Issue by jcvdav** [kristafinlay/issues-lab#1]
Code here calls a dataset named `storm`, but the built-in data might be called `storms`? Perhaps try changing the name here.

https://github.com/kristafinlay/issues-lab/blob/3f4d7131e47a6e7732f0ab3d5a47ea07dd4e23b7/got_issues.Rmd#L18

**Comment by kristafinlay** [comment]
resolved

**Comment by kristafinlay** [comment]
resolved correctly
